{
  "swagger": "2.0",
  "info": {
    "title": "Microsoft Graph",
    "description": "",
    "version": "1.0"
  },
  "host": "graph.microsoft.com",
  "basePath": "/",
  "schemes": [
    "https"
  ],
  "paths": {
    "/v1.0/me": {
      "get": {
        "summary": "Me",
        "operationId": "Me"
      }
    },
    "/v1.0/me/drive/root:/{documentPath}:/workbook/createSession": {
      "post": {
        "summary": "Create a new workbook session.",
        "operationId": "CreateSession",
        "description": "https://learn.microsoft.com/en-us/graph/api/workbook-createsession?view=graph-rest-1.0&tabs=http"
      }
    },
    "/v1.0/me/drive/root:/{documentPath}:/workbook/closeSession": {
      "post": {
        "summary": "Close an existing workbook session.",
        "operationId": "CloseSession",
        "description": "https://learn.microsoft.com/en-us/graph/api/workbook-closesession?view=graph-rest-1.0&tabs=http"
      }
    },
    "/v1.0/me/drive/root:/{documentPath}:/workbook/worksheets/{sheetName}/range(address='{address}')": {
      "get": {
        "summary": "Retrieve the properties and relationships of range object",
        "operationId": "GetRange",
        "description": "https://learn.microsoft.com/en-us/graph/api/range-get?view=graph-rest-1.0&tabs=http"
      }
    },
    "/v1.0/me/drive/root:/{documentPath}:/workbook/tables/{tableName}/rows/add": {
      "post": {
        "summary": "Add a row in a table",
        "operationId": "AddTableRow",
        "description": "https://learn.microsoft.com/en-us/graph/api/tablerowcollection-add?view=graph-rest-1.0&tabs=http"
      }
    },
    "/v1.0/me/drive/root:/{documentPath}:/workbook/tables/{tableName}/headerRowRange": {
      "get": {
        "summary": "Get the range object associated with header row of the table",
        "operationId": "GetTableHeaderRowRange",
        "description": "https://learn.microsoft.com/en-us/graph/api/table-headerrowrange?view=graph-rest-1.0&tabs=http"
      }
    },
    "/v1.0/me/drive/root:/{documentPath}:/workbook/tables/{tableName}/dataBodyRange": {
      "get": {
        "summary": "Get the range object associated with the data body of the table",
        "description": "https://learn.microsoft.com/en-us/graph/api/table-databodyrange?view=graph-rest-1.0&tabs=http",
        "operationId": "GetTableDataBodyRange"
      }
    },
    "/v1.0/me/drive/root:/{documentPath}:/workbook/tables/{tableName}/rows": {
      "get": {
        "summary": "Get the rows in a table",
        "operationId": "GetTableRows",
        "description": "https://learn.microsoft.com/en-us/graph/api/table-list-rows?view=graph-rest-1.0&tabs=http"
      }
    },
    "/v1.0/me/drive/root:/{documentPath}:/workbook/tables/{tableName}/rows/itemAt(index={index})": {
      "get": {
        "operationId": "GetTableRow",
        "summary": "Get a row based on its position in the collection",
        "description": "https://learn.microsoft.com/en-us/graph/api/tablerowcollection-itemat?view=graph-rest-1.0&tabs=http"
      },
      "delete": {
        "summary": "Delete a row from the table",
        "operationId": "DeleteTableRow",
        "description": "https://learn.microsoft.com/en-us/graph/api/tablerow-delete?view=graph-rest-1.0&tabs=http"
      }
    },
    "/v1.0/me/drive/root:/{documentPath}:/workbook/tables/{tableName}/columns/{nameOrIndex}": {
      "get": {
        "operationId": "GetTableColumn",
        "summary": "Get a table column",
        "description": "https://learn.microsoft.com/en-us/graph/api/tablecolumn-get?view=graph-rest-1.0&tabs=http"
      }
    },
    "/v1.0/me/drive/root:/{documentPath}:/workbook/tables/{tableName}/columns/{nameOrId}/dataBodyRange": {
      "get": {
        "operationId": "GetTableColumnDataBodyRange",
        "summary": "Get the range object associated with the data body of the column",
        "description": "https://learn.microsoft.com/en-us/graph/api/tablecolumn-databodyrange?view=graph-rest-1.0&tabs=http"
      }
    },
    "/v1.0/me/drive/root:/{documentPath}:/workbook/worksheets/{worksheetName}/pivotTables/{tableName}/refresh": {
      "post": {
        "operationId": "RefreshPivotTable",
        "summary": "Refresh a PivotTable",
        "description": "https://learn.microsoft.com/en-us/graph/api/workbookpivottable-refresh?view=graph-rest-1.0&tabs=http"
      }
    },
    "/v1.0/me/drive/root:/{documentPath}:/workbook/tables/{tableName}/columns": {
      "get": {
        "operationId": "GetTableColumns",
        "summary": "Retrieve a list of columns in a table",
        "description": "https://learn.microsoft.com/en-us/graph/api/tablecolumn-list?view=graph-rest-1.0&tabs=http"
      }
    }
  },
  "securityDefinitions": {
    "oauth2-auth": {
      "type": "oauth2",
      "flow": "accessCode",
      "tokenUrl": "https://login.windows.net/common/oauth2/authorize",
      "scopes": {
        "Files.Read Files.Read.All Files.ReadWrite Files.ReadWrite.All user.read mail.read offline_access": "Files.Read Files.Read.All Files.ReadWrite Files.ReadWrite.All user.read mail.read offline_access"
      },
      "authorizationUrl": "https://login.microsoftonline.com/common/oauth2/authorize"
    }
  },
  "security": [
    {
      "oauth2-auth": [
        "Files.Read Files.Read.All Files.ReadWrite Files.ReadWrite.All user.read mail.read offline_access"
      ]
    }
  ],
  "tags": []
}